name: check-format

on:
  push:
    branches:
      - "**"

  workflow_dispatch:

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: jidicula/clang-format-action@v4.6.2
        with:
          clang-format-version: '14'
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - run: pip install black
      - run: black --check -l 110 tests
