name: Run tests

on:
  push:
    branches:
      - "**"
  
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: nickeldan/scrutiny:0.5.2
    steps:
      - uses: actions/checkout@v3
      - run: make tests
